# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/edabk2003/data/kien/TKS/ibex_zcu104/vivado/vivado.runs/synth_1/top_zcu104.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/edabk2003/data/kien/TKS/ibex_zcu104/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /media/edabk2003/data/kien/TKS/ibex_zcu104/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_output_repo /media/edabk2003/data/kien/TKS/ibex_zcu104/vivado/vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_sec_cm.svh
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_dummy_macros.svh
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.svh
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_pmp_reset_default.svh
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_util_memload.svh
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_util_get_scramble_params.svh
}
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_sec_cm.svh]
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_dummy_macros.svh]
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.svh]
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_pmp_reset_default.svh]
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_util_memload.svh]
set_property file_type "Verilog Header" [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_util_get_scramble_params.svh]
read_verilog -library xil_defaultlib -sv {
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/shared/rtl/bus.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/debounce.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dm_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dm_csrs.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/sva/dm_csrs_sva.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dm_mem.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dm_sba.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/sva/dm_sba_sva.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_flop_macros.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/dm_top.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/sva/dm_top_sva.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/gpio.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_alu.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_branch_predict.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_compressed_decoder.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_controller.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_core.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_counter.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_csr.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_decoder.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/jtag_id_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/ibex_demo_system.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_dummy_instr.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_ex_block.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_fetch_fifo.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_icache.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_if_stage.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_load_store_unit.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_multdiv_fast.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_multdiv_slow.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_pmp.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_prefetch_buffer.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_register_file_ff.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_register_file_latch.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_top.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/rtl/ibex_wb_stage.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_and2.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_buf.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_clock_gating.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_clock_mux2.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_async_simple.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_sync.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_sync_cnt.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_flop.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_flop_2sync.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_and2.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_buf.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_gating.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_inv.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_flop.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_ram_1p.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_2p_pkg.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_ram_2p.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_check.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_mux.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_prince.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/dv/uvm/core_ibex/common/prim/prim_ram_1p.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_adv.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_subst_perm.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim/rtl/prim_sync_reqack.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_clock_gating.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/pwm.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/pwm_wrapper.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/shared/rtl/ram_2p.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/fpga/rst_ctrl.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/spi_host.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/spi_top.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/vendor/lowrisc_ibex/shared/rtl/timer.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/uart.sv
  /media/edabk2003/data/kien/TKS/ibex_zcu104/rtl/fpga/top_zcu104.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/edabk2003/data/kien/TKS/ibex_zcu104/data/pins_zcu104.xdc
set_property used_in_implementation false [get_files /media/edabk2003/data/kien/TKS/ibex_zcu104/data/pins_zcu104.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /media/edabk2003/data/kien/TKS/ibex_zcu104/vivado/vivado.srcs/utils_1/imports/synth_1/top_sonata.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_zcu104 -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_zcu104.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_zcu104_utilization_synth.rpt -pb top_zcu104_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
